### ISSUE TITLE
Does not work for '-f -r resource'

### ISSUE THREAD

**Issue by 10uei011** [eveningkid/args-parser#3]
if i use 'node script.js -f -r resource' i am expecting 
{
  f: true,
  r: resource 
}
Instead I am getting 
{
  f: true,
  r: true,
  resource: true
}

**Comment by eveningkid** [comment]
Hi @10uei011,

Thanks for your interest! You encountered this issue as this module's valid syntax would be the following: `$ node ./script.js -f -r=resource`.

It wasn't designed to understand what you want to parse, as `args-parser` splits the string using whitespaces. 

This feature could definitely be added if you want to work on it —I'd really appreciate it.
Otherwise, either change the way you pass arguments to your program or don't use this module as it doesn't fit your expectations.
